### ISSUE TITLE
Missing python311.dll

### ISSUE THREAD

**Issue by dfeneck** [GregoryAM-SP/The-Minecraft-Overviewer#14]
First I'd just like to thank you for picking up the project and keeping it alive, Overviewer has always been a favourite tool of ours. I have it configured to run weekly at http://themotherland.ddns.net:8317/map

When I try to run your new version, v1.20.1, I get the following error messages:
`The program can't start because api-ms-win-core-path-l1-1-0.dll is missing from your computer`
`Error loading Python DLL <path-to-overviewer>\python311.dll`

I can supply api-ms-win-core-path-l1-1-0.dll and that message goes away, but supplying python311.dll does nothing.

I've seen the notice that Python 3.6 is now required, but this message I'm getting would suggest it needs python v3.11? Which is a problem for me since my server still runs on Windows 7, and python drops support for it at 3.8.

Am I doing something wrong? Or has the requirements shifted again to need Window 10 or higher with Python 3.11?

**Comment by Gregory-AM** [comment]
Hey, Sorry for the late reply.
So you're running Windows 7 with Python v3.8? If I understand this correctly.

**Comment by dfeneck** [comment]
I'm running Windows 7 with Python 3.6
(3.8 is just as far as windows 7 can go)

**Comment by Gregory-AM** [comment]
I'm looking for a download to 3.8.17 of python.
Which on their website doesn't seem to be available in an installer.

**Comment by JoshuaMarti** [comment]
https://www.python.org/downloads/release/python-3810/

Python 3.8.10 was the last release of Python 8 with Windows installers.

**Comment by Gregory-AM** [comment]
Thank you for that.
I went ahead and got 3.8.5 at the moment.
I'll update to that version after my build.
I'll continue to develop Overviewer with 3.8.10 afterwards to make sure I continue support for Win7.

Thank you for bringing this up to my attention!

**Comment by Gregory-AM** [comment]
https://github.com/GregoryAM-SP/The-Minecraft-Overviewer/releases/tag/v1.20.2
Let me know if there are any issues with this release.
