### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by Unix-User** [GregoryAM-SP/The-Minecraft-Overviewer#15]
I wanted to make a modification to get the player names from usercache.json so I cloned the repo and tried to build here but I'm getting the error "command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community \\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX86\\x86\\cl.exe' failed with exit status 2", using python 3.8, using 3.7 it compiles with some warnings, but when running it keeps asking vcredist_2008/2010, I'm not an expert in C++ or python, I'm not sure if I'm skipping a step, could you provide more detailed instructions?

**Comment by Gregory-AM** [comment]
Hey, @Unix-User!
Which operating system are you on?

**Comment by Gregory-AM** [comment]
Hey, @Unix-User.
It looks like you're missing VSCode Community Edition with Windows Build Tools.
You can [download it here](https://visualstudio.microsoft.com/vs/community/)

If you've already downloaded the VSCode Community Edition and you already set it up,
You will need to run the Visual Studio Installer, modify the Community Edition,
make sure Desktop Development with C++ is selected.

This should install the VC++ versions.

I've noticed on the original overviewer documentation the VC++ 2008 & 2010 versions links are dead.

**Comment by Gregory-AM** [comment]
If you have a Discord account, add me on there [@]GregoryAM without the brackets.
