### ISSUE TITLE
biome support request

### ISSUE THREAD

**Issue by dalandis** [GregoryAM-SP/The-Minecraft-Overviewer#3]
First of all, I express my gratitude to all those who did not leave the project without support and are going to develop it.

Is it possible to pull changes from here https://github.com/granis/Minecraft-Overviewer ?
to support biomes on the map

**Comment by Gregory-AM** [comment]
Hey, I appreciate you reaching out and letting me know about this.
I'll take a look at the repo, and see which files are modified, and pull from it when I get the chance too.

I'm currently working towards getting faster render times.

**Comment by dalandis** [comment]
Thank you.
In the same fork there are small changes for speed, maybe this will help somehow. But in my experience, if there is an acceleration, it is negligible.

**Comment by cliffmeyers** [comment]
@dalandis might be helpful if you opened a pull request with the changes that you think would be good to merge?

**Comment by Gregory-AM** [comment]
@dalandis, looking into the code from the Repo you've mentioned:
- LRUCache causes RAM Usage to increase but doesn't allow faster rendering time. 
( The Repo has the original LRUCache as the OG Overviewer, and what my current file has, so it's unchanged)
- While you have added in the Biome settings (Temp, Rainfall, & Colors). The best thing to do is do what @cliffmeyers mentioned. Open a Pull Request with the specific changes you would like to see.
**Note:** This is already being worked on alongside quicker render times, and adding in other blocks. But, If the work in that Repo is completed with **every** Biome supported, the merge is more likely to happen.
- You've changed the way Grass Blocks and Snow Blocks render in ( as Full Blocks ).
While this is a nice visual change, it defeats what Overviewer is when showing the Original Minecraft Map.
This modification isn't something I will incorporate.
