### ISSUE TITLE
Request to add support for Minecraft Bedrock Edition maps

### ISSUE THREAD

**Issue by barrett777** [GregoryAM-SP/The-Minecraft-Overviewer#4]
It would be great to support Minecraft Bedrock maps in Overviewer.

A while ago I got started trying to support Bedrock maps in Overviewer: https://github.com/overviewer/Minecraft-Overviewer/pull/2044

I ran into some issues I couldn't easily overcome, so I gave up :)

At this time I'm probably not able to contribute myself, but if anyone on your end is inspired, please feel free to take any useful bits of code I got started with in the above PR

**Comment by Gregory-AM** [comment]
I checked out the pull request you made on the original Overviewer where you introduced the idea of using PyMCTranslate.
While it would be a great addition to add into Overviewer, the only way this would be achieved is if someone made PyMCTranslate into a Plugin for Overviewer.

With little or no documentation on how to create Plugins for Overviewer, this will present itself to be a challenge.

But, overall, I will be looking into creating Plugins and Extras that can work with Overviewer.
It might just be **awhile** until I figure it out.

But here's two Plugins and Extras I want to add:
- Support for Bedrock
- Support for Modded Blocks
