### ISSUE TITLE
Live non-waterlogged coral rendering as water block

### ISSUE THREAD

**Issue by stwalkerster** [GregoryAM-SP/The-Minecraft-Overviewer#41]
When a `minecraft:*_coral` block is currently rendered, it's rendered as a water block no matter the state of the `waterlogged` property. If `waterlogged: false`, it should render as a nice, colourful coral plant.

![image](https://github.com/GregoryAM-SP/The-Minecraft-Overviewer/assets/722710/07f891be-4a5f-48d2-93c6-675c2999a081)
![image](https://github.com/GregoryAM-SP/The-Minecraft-Overviewer/assets/722710/8ece96ee-10c3-4a29-a583-33a18337fd94)

**Comment by Gregory-AM** [comment]
✅ `minecraft:*_coral`
✅ `minecraft:*_coral_fan`
✅ `minecraft:dead_*_coral`
✅ `minecraft:dead_*_coral_fan`

When a coral block is placed on a waterlogged slab / block, they now show their vibrant colors.
 
![Screenshot 2024-02-11 032554](https://github.com/GregoryAM-SP/The-Minecraft-Overviewer/assets/83489100/33933488-9bf8-4a9f-b864-d4c999c15ff9)
