### ISSUE TITLE
Dead coral fans on a wall don't render

### ISSUE THREAD

**Issue by stwalkerster** [GregoryAM-SP/The-Minecraft-Overviewer#42]
This affects the following block IDs:
- `minecraft:dead_tube_coral_wall_fan`
- `minecraft:dead_brain_coral_wall_fan`
- `minecraft:dead_bubble_coral_wall_fan`
- `minecraft:dead_fire_coral_wall_fan`
- `minecraft:dead_horn_coral_wall_fan`

Note that the floor-based versions of these blocks do render

There's potentially some code related to Amethyst that might be reusable

**Comment by Gregory-AM** [comment]
`minecraft:dead_%_coral_wall_fan`
`minecraft:%_coral_wall_fan`

These now render but need testing for their rotations in different northdirections*.

* I will be testing them after I create a configuration file
