### ISSUE TITLE
Candles do not render

### ISSUE THREAD

**Issue by stwalkerster** [GregoryAM-SP/The-Minecraft-Overviewer#43]
This affects the following block IDs:
- minecraft:black_candle
- minecraft:lime_candle
- minecraft:pink_candle
- minecraft:gray_candle
- minecraft:light_gray_candle
- minecraft:cyan_candle
- minecraft:candle
- minecraft:purple_candle
- minecraft:white_candle
- minecraft:blue_candle
- minecraft:orange_candle
- minecraft:brown_candle
- minecraft:magenta_candle
- minecraft:green_candle
- minecraft:light_blue_candle
- minecraft:red_candle
- minecraft:yellow_candle

Bear in mind that candles can come on their own, in a pair, triplet, or quadruplet. We can probably ignore the lit and waterlogged states for the time being.

**Comment by Gregory-AM** [comment]
I have these currently rendering off of the item.
I will be working to make them 3D in the near future.
