### ISSUE TITLE
Candle cakes do not render

### ISSUE THREAD

**Issue by stwalkerster** [GregoryAM-SP/The-Minecraft-Overviewer#44]
This affects the following block IDs
- minecraft:candle_cake
- minecraft:white_candle_cake
- minecraft:orange_candle_cake
- minecraft:magenta_candle_cake
- minecraft:light_blue_candle_cake
- minecraft:yellow_candle_cake
- minecraft:lime_candle_cake
- minecraft:pink_candle_cake
- minecraft:gray_candle_cake
- minecraft:light_gray_candle_cake
- minecraft:cyan_candle_cake
- minecraft:purple_candle_cake
- minecraft:blue_candle_cake
- minecraft:brown_candle_cake
- minecraft:green_candle_cake
- minecraft:red_candle_cake
- minecraft:black_candle_cake

The only block state of relevance is the `lit` state, which we can probably ignore for the time being

**Comment by Gregory-AM** [comment]
Similar to the candles rendering in #43:
I have these currently rendering off of the item.
I will be working to make them 3D in the near future.

The candle cakes now render.
