### ISSUE TITLE
TMO is unable to generate chunks with custom biomes

### ISSUE THREAD

**Issue by artur9010** [GregoryAM-SP/The-Minecraft-Overviewer#67]
It should at least fallback to some default biome type

```
prepare-files-1 exited with code 0
overviewer-1     | 2024-05-07 20:34:46  Generating textures...
overviewer-1     | *******************************************************************************
overviewer-1     | 2024-05-07 20:35:04 W There was a problem reading chunk 7,4.  It might be corrupt.  I am giving up and will not render this particular chunk.
overviewer-1     | *******************************************************************************
overviewer-1     | 2024-05-07 20:35:04 E An error has occurred. This may be a bug. Please let us know!
overviewer-1     | See http://docs.overviewer.org/en/latest/index.html#help
overviewer-1     | 
overviewer-1     | This is the error that occurred:
overviewer-1     | Traceback (most recent call last):
overviewer-1     |   File "overviewer_core/world.py", line 2270, in get_chunk
overviewer-1     |   File "overviewer_core/world.py", line 1924, in _get_biomedata_v118
overviewer-1     | ValueError: 'terra:overworld/overworld/sakura_mountains' is not in list
overviewer-1     | 
overviewer-1     | During handling of the above exception, another exception occurred:
overviewer-1     | 
overviewer-1     | Traceback (most recent call last):
overviewer-1     |   File "overviewer.py", line 662, in <module>
overviewer-1     |   File "overviewer.py", line 571, in main
overviewer-1     |   File "overviewer_core/world.py", line 221, in find_true_spawn
overviewer-1     |   File "overviewer_core/world.py", line 2292, in get_chunk
overviewer-1     | overviewer_core.nbt.CorruptChunkError
overviewer-1 exited with code 1
```

**Comment by Gregory-AM** [comment]
The Minecraft Overviewer is meant for 100% Vanilla Minecraft.

Custom Biomes and Blocks are not supported at all.

This would require hard coding ALL blocks and biomes from all available Mods, Modpacks, and Data Packs.

---

I do like the idea of defaulting to a "default" biome if a custom biome is unavailable.

It's been a minute since I've had time to work on this, due to work and school. So, I'll get to this as soon as possible!

**Comment by stwalkerster** [comment]
I may have to have a play around with it, but I'm not sure what would happen if we just dynamically appended custom biomes to the list `RegionSet._biomemap` when we hit the `KeyError` at world.py:1925 .

For the time being, @Gregory-AM is correct that we don't really support custom biomes yet. That said, I am curious to take a look and see if we can modify Overviewer to not explode when it encounters a custom biome.

@artur9010 - your initial description doesn't really give much in the way of detail. Please can you give us the infomation needed to recreate the issue ourselves from scratch? This probably includes (but not limited to) the Minecraft version, the Overviewer version, any mods and/or datapacks which affect terrain generation (or just list them all), and your Overviewer configuration file (stripped of any private data like paths etc)

**Comment by artur9010** [comment]
It's a paper 1.20.4 server running with custom generator Terra - https://modrinth.com/plugin/terra
Running overviewer from main branch

```
texturepath = "/mnt/minecraft/.minecraft/versions/1.20.4/1.20.4.jar"

worlds['My World'] = "/usr/overviewer/server/world"

outputdir = "/usr/overviewer/output"

rendermode = "lighting"



renders["render1"] = {
        'world': 'My World',
        'title': 'A regular render',
}
```

**Comment by stwalkerster** [comment]
Thanks - I'll try and dig in a bit over the next few days to see if a fix is going to be as simple as I think it might be. I'm not too interested in fully supporting custom biomes at the moment, but I am interested in making Overviewer not crash on unknown biomes.

**Comment by artur9010** [comment]
`but I am interested in making Overviewer not crash on unknown biomes`

That's enough for me, I don't care about custom biome colors on webmap 😄  Thanks

**Comment by Gregory-AM** [comment]
I'll work on making a better Issue Template, so we don't have to come into the comments and ask more questions like this.

I've been meaning to do this for some time but haven't figured out the right questions to add to the template.

**Comment by stwalkerster** [comment]
![image](https://github.com/GregoryAM-SP/The-Minecraft-Overviewer/assets/722710/34ed8062-7ada-4d0f-965f-ec6946e9c655)

Seems to work fine with by just treating all biomes as `minecraft:plains`. It's not going to have any of the biome-specific vegetation shading, nor will the biome type overlay work properly, but I think that'll need to wait for proper mod support within Overviewer itself.

**Comment by artur9010** [comment]
Can confirm it runs, thanks.

```
~/overviewer# docker logs 9047803c45f3
2024-05-11 21:06:08  Welcome to Minecraft Overviewer version unknown (19e9695)!
2024-05-11 21:06:08  Generating textures...
2024-05-11 21:06:27  Preprocessing...
2024-05-11 21:07:42  Rendered 0 of 103249.  0% complete.  ETA: ------
2024-05-11 21:08:11  Rendered 10 of 103249.  0% complete.  ETA: 83h 32m 46s
2024-05-11 21:08:15  Rendered 20 of 103249.  0% complete.  ETA: 47h 26m 25s
2024-05-11 21:08:19  Rendered 30 of 103249.  0% complete.  ETA: 35h 57m 37s
2024-05-11 21:08:24  Rendered 40 of 103249.  0% complete.  ETA: 30h 14m 58s
2024-05-11 21:08:28  Rendered 50 of 103249.  0% complete.  ETA: 26h 30m 53s
2024-05-11 21:08:31  Rendered 60 of 103249.  0% complete.  ETA: 23h 23m 34s
2024-05-11 21:08:33  Rendered 70 of 103249.  0% complete.  ETA: 21h 09m 58s
2024-05-11 21:08:37  Rendered 80 of 103249.  0% complete.  ETA: 19h 57m 47s
2024-05-11 21:08:39  Rendered 90 of 103249.  0% complete.  ETA: 18h 23m 10s
2024-05-11 21:08:43  Rendered 100 of 103249.  0% complete.  ETA: 17h 36m 32s
2024-05-11 21:08:56  Rendered 150 of 103249.  0% complete.  ETA: 14h 13m 44s
2024-05-11 21:09:13  Rendered 201 of 103249.  0% complete.  ETA: 13h 02m 28s
2024-05-11 21:09:28  Rendered 251 of 103249.  0% complete.  ETA: 12h 05m 22s
```
