### ISSUE TITLE
Python 3.12 support?

### ISSUE THREAD

**Issue by Th3Bobo** [GregoryAM-SP/The-Minecraft-Overviewer#74]
Hi I’m running in to some issues.

> ModuleNotFoundError: No module named 'distutils'

And

> ModuleNotFoundError: No module named 'imp' line 21, in <module>
>     import imp
> ModuleNotFoundError: No module named 'imp'
> 

The fist one: 

"[gh-95299](https://github.com/python/cpython/issues/95299): Do not pre-install setuptools in virtual environments created with venv. This means that distutils, setuptools, pkg_resources, and easy_install will no longer available by default; to access these run pip install setuptools in the activated virtual environment"

Not a big issue I just installed setuptools with 

`pip3 install setuptools`

 But the second one:

"DeprecationWarning: the imp module is deprecated in favour of importlib and 
slated for removal in Python 3.12; see the module's documentation for 
alternative uses"

I don’t see that it is as an easy fix with imp. Am I misunderstanding this or can I do anything other than installing an older version of python?

Thank you for all your help.

**Comment by Gregory-AM** [comment]
Hey, @Th3Bobo.
Sorry for the late reply!

<hr>

The Minecraft Overviewer **_only_** supports Python 3.8.10 as stated in the [README](https://github.com/GregoryAM-SP/The-Minecraft-Overviewer/blob/main/README.md#python-3810-required) as a requirement.

While we do have it noted that we should update to a newer version of Python; we cannot guarantee this will happen or be done.

<hr>

You are welcome to clone / fork the project and make the implementations yourself to support Python 3.12 as this is not fully planned on our end, just noted down.

**Any changes made on our end will be reflected in the README, Commit logs, and Release Notes.**

**Comment by Th3Bobo** [comment]
Hi @Gregory-AM 
Thank you for your reply.
I am sorry I thought I had read the README thoroughly, my misstake.
Thank you for all your work.
