### ISSUE TITLE
Sections of Map not rendering

### ISSUE THREAD

**Issue by davidjmerritt** [GregoryAM-SP/The-Minecraft-Overviewer#75]
We are running Minecraft Server v1.20.2 on a Linux machine.  The overviewer runs an updates with no error messages but some sections of the map are empty.  Any idea on why this is happening?

**Comment by stwalkerster** [comment]
Hi, I'm afraid we're going to need a bunch more info to try reproducing this.

* What version of Overviewer are you running?
* What version of Python are you running?
* Is it Vanilla Minecraft? Has the world been updated from older versions, or is it new on 1.20?
* What do the "empty sections" look like? Are they [square 384x384](https://mcmaps.fastlizard4.org/s2/myrender/3/0/0/0/0/0/0/2/1.jpg) pixel images (tiles) or does it look like world data that's missing?
* Do you get similar behaviour on a freshly-generated world, or is it only your specific world?

**Comment by stwalkerster** [comment]
I've closed this for now as we don't have enough information to understand the problem.
